# Generated by Django 4.1.4 on 2022-12-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_project_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'IpClient',
            },
        ),
    ]
